spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:${user.home}/.authenticator/keys/private-key.pem}